
LEFT_LEG_HIP_PITCH_ID = 31
LEFT_LEG_HIP_ROLL_ID = 32
LEFT_LEG_THIGH_ID = 33
LEFT_LEG_KNEE_ID = 34
LEFT_LEG_FOOT_ID = 35

RIGHT_LEG_HIP_PITCH_ID = 41
RIGHT_LEG_HIP_ROLL_ID = 42
RIGHT_LEG_THIGH_ID = 43
RIGHT_LEG_KNEE_ID = 44
RIGHT_LEG_FOOT_ID = 45

RIGHT_LEG_JOINT_IDS = [
    RIGHT_LEG_HIP_PITCH_ID,
    RIGHT_LEG_HIP_ROLL_ID,
    RIGHT_LEG_THIGH_ID,
    RIGHT_LEG_KNEE_ID,
    RIGHT_LEG_FOOT_ID,
]

LEFT_LEG_JOINT_IDS = [
    LEFT_LEG_HIP_PITCH_ID,
    LEFT_LEG_HIP_ROLL_ID,
    LEFT_LEG_THIGH_ID,
    LEFT_LEG_KNEE_ID,
    LEFT_LEG_FOOT_ID,
]

ALL_LEG_JOINT_IDS = LEFT_LEG_JOINT_IDS + RIGHT_LEG_JOINT_IDS